def printMenu():
    print("\n--------- MENU ----------")
    print("| [1] - INSERT DATA\t|")
    print("| [2] - PRINT ALL DATA\t|")
    print("| [3] - ALTER DATA\t|")
    print("| [4] - EXCLUDE DATA\t|")
    print("| [5] - CLASSIFY\t|")
    print("| [6] - PURGE ALL DATA!\t|")
    print("| [0] - QUIT\t\t|")
    print("-------------------------")
    print("Type desired option:")